/*
 * This source file was generated by the Gradle 'init' task
 */
package me.rainma22.dillydally;

import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpsServer;
import me.rainma22.dillydally.conf.ConfBean;
import me.rainma22.dillydally.handler.FileHandler;
import me.rainma22.dillydally.sslcert.challengecompletion.ChallengeCompletors;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONException;
import org.json.JSONObject;

public class Server {

    private static final Logger LOGGER = LogManager.getLogger();

    private static final Path configDirPath = Path.of("config");
    private static final Path configJson = configDirPath.resolve("config.json");
    private static ConfBean config = new ConfBean();

    public static void main(String[] args) throws Exception {
        try {
            Files.createDirectories(configDirPath);
        } catch (IOException ie) {
            // ignored
        }
        boolean confExisted = Files.exists(configJson);
        if (confExisted) {
            try {
                config = new JSONObject(Files.readString(configJson)).fromJson(ConfBean.class);
            } catch (JSONException | IOException e) {
                // ignored
            }
        }
        Files.writeString(configJson, new JSONObject(config).toString(4));
        if (!confExisted) {
            System.out.println();
            System.out.printf("Config file did not exist in %s. We generated a default. \n", configJson);
            System.out.println("Please configure the file");
            System.out.print("This program will exit in 3 seconds");
            for (int i = 0; i < 3; i++) {
                Thread.sleep(Duration.ofSeconds(1));
                System.out.print(".");
            }
            System.out.println();
            return;
        }
        try {
            DillyDally dd = new DillyDally(config);
            HttpServer http = dd.createHttp();
            var handlerLayout = config.getHandlerLayout();
            if (config.isDoHttps()) {
                ChallengeCompletors.setHttpServer(http);
                // TODO: pending removal after removal of File-based HTTP-01 completor
                HttpHandler handler = new FileHandler(Path.of(config.getSslCertificateConf().getPathToWebRootDir()));
                http.createContext("/", handler);
                http.start();
                // END TODO: pending removal after removal of File-based HTTP-01 completor

                HttpsServer https = dd.createHttps();
                // TODO: pending removal after removal of File-based HTTP-01 completor
                http.stop(0);
                http = dd.createHttp();
                // END TODO: pending removal after removal of File-based HTTP-01 completor
                for (var e : handlerLayout.entrySet()) {
                    var k = e.getKey();
                    var v = e.getValue();
                    http.createContext(k, v);
                    https.createContext(k, v);
                }
                http.start();
                https.start();
                LOGGER.always().log("Http Server Started at http://" + "0.0.0.0:" + config.getHttpPort());
                LOGGER.always().log("Https Server Started at https://" + "0.0.0.0:" + config.getHttpsPort());
            } else {
                for (var e : handlerLayout.entrySet()) {
                    var k = e.getKey();
                    var v = e.getValue();
                    http.createContext(k, v);
                }
                http.start();
                LOGGER.always().log("Http Server Started at http://" + "0.0.0.0:" + config.getHttpPort());
            }
        } catch (IOException ie) {
            LOGGER.error(ie);
            return;
        }

    }
}
