/*
 * This source file was generated by the Gradle 'init' task
 */
package me.rainma22.dillydally;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import org.json.JSONException;
import org.json.JSONObject;

public class Server {

    private static final Path configDirPath = Path.of("config");
    private static final Path configJson = configDirPath.resolve("config.json");
    private static ConfBean config = new ConfBean();
    private static HttpServer server = null;

    public static void main(String[] args) {
        try {
            Files.createDirectory(configDirPath);
        } catch (IOException ie) {
            ie.printStackTrace();
        }

        try {
            config = new JSONObject(configJson.toFile()).fromJson(ConfBean.class);
        } catch (JSONException je) {
            //ignored
        }
        try (var channel = Files.newByteChannel(configJson)) {
            channel.write(ByteBuffer.wrap(new JSONObject(config)
                    .toString()
                    .getBytes()));
            server = HttpServer.create(new InetSocketAddress(config.getHttpPort()), 0);
        } catch (IOException ie) {
            ie.printStackTrace();
            return;
        }
        
    }
}
