/*
 * This source file was generated by the Gradle 'init' task
 */
package me.rainma22.dillydally;

import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpsServer;
import me.rainma22.dillydally.conf.ConfBean;
import me.rainma22.dillydally.handler.FileHandler;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONException;
import org.json.JSONObject;

public class Server {

    private static final Logger LOGGER = LogManager.getLogger();

    private static final Path configDirPath = Path.of("config");
    private static final Path configJson = configDirPath.resolve("config.json");
    private static ConfBean config = new ConfBean();

    public static void main(String[] args) throws Exception {
        try {
            Files.createDirectories(configDirPath);
        } catch (IOException ie) {
            // ignored
        }
        try {
            config = new JSONObject(Files.readString(configJson)).fromJson(ConfBean.class);
        } catch (JSONException | IOException e) {
            // ignored
        }
        Files.writeString(configJson, new JSONObject(config).toString(4));

        try {
            DillyDally dd = new DillyDally(config);
            HttpServer http = dd.createHttp();
            HttpHandler handler = new FileHandler(Path.of(config.getFileHandlerConf().getDirectoryPath()));
            http.createContext("/", handler);
            http.start();
            LOGGER.always().log("Http Server Started at http://" + "0.0.0.0:" + config.getHttpPort());

            HttpsServer https = dd.createHttps();
            https.createContext("/", handler);
            https.start();
            LOGGER.always().log("Https Server Started at https://" + "0.0.0.0:" + config.getHttpsPort());
        } catch (IOException ie) {
            LOGGER.error(ie);
            return;
        }

    }
}
